"""Data-access functions: the only place SQL is written.

Every function is scoped by ``user_id`` (the FX cache excepted — ECB rates
are public and identical for every user), and returns domain objects, not
ORM rows, via :mod:`traccio.db.mappers`.

Split from one 3000-line module into a submodule per domain concern
(2026-09-07). Every public name is re-exported here, so existing
``from traccio.db.repositories import X`` imports are unchanged.
"""

from traccio.db.repositories.accounts import (
    account_has_transactions,
    create_manual_account,
    delete_manual_account,
    get_account,
    list_accounts,
    set_account_alias,
    set_account_appearance,
    set_account_kind,
    upsert_account,
)
from traccio.db.repositories.advances import (
    advance_exists_for_transaction,
    create_advance,
    create_reimbursement,
    delete_advance,
    delete_reimbursement,
    get_advance,
    list_advances,
    list_reimbursements,
    set_advance_status,
    sum_reimbursements_by_advance,
    sum_reimbursements_by_participant,
)
from traccio.db.repositories.categories import (
    category_has_children,
    category_is_confirmed_on_any_transaction,
    category_name_exists,
    create_category,
    delete_category,
    get_category,
    list_categories,
    list_child_category_ids,
    move_category,
    rename_category,
    seed_default_categories,
    set_category_appearance,
)
from traccio.db.repositories.connections import (
    activate_connection,
    create_connection,
    find_pending_connection_id,
    get_connection,
    get_connection_credentials,
    list_connections,
    list_connections_without_logo,
    mark_connection_synced,
    set_connection_auth_state,
    set_connection_logo,
)
from traccio.db.repositories.events import (
    assign_transaction_to_event,
    create_event,
    delete_event,
    event_ids_for_transactions,
    get_event,
    get_transaction_event_id,
    list_event_candidates,
    list_event_members,
    list_events,
    set_event_status,
    unassign_transaction_from_event,
    update_event,
)
from traccio.db.repositories.fx import (
    get_fx_rates,
    latest_fx_rate_fetched_at,
    upsert_fx_rates,
)
from traccio.db.repositories.imports import (
    create_imported_transactions,
    imported_stable_keys,
)
from traccio.db.repositories.rules import (
    create_rule,
    delete_rule,
    delete_rules_for_category,
    get_rule,
    list_rules,
    rule_exists,
)
from traccio.db.repositories.settings import (
    earliest_transaction_dates_by_account,
    get_meal_vouchers_enabled,
    get_tracking_start_date,
    set_meal_vouchers_enabled,
    set_tracking_start_date,
)
from traccio.db.repositories.sync_runs import (
    count_recent_sync_runs,
    list_sync_runs,
    oldest_recent_sync_run_started_at,
    record_sync_run,
)
from traccio.db.repositories.transactions import (
    create_manual_transaction,
    delete_manual_transaction,
    get_transaction,
    list_all_transactions,
    list_transactions,
    list_transactions_by_ids,
    list_transactions_in_period,
    prune_stale_pending_transactions,
    set_confirmed_category,
    set_suggested_categories,
    set_transaction_role,
    transaction_is_linked,
    update_manual_transaction,
    upsert_transaction,
)
from traccio.db.repositories.transfers import (
    create_transfer,
    create_transfer_dismissal,
    delete_transfer,
    list_transfer_dismissals,
    list_transfers,
    transfer_exists_for_transaction,
)

__all__ = [
    "account_has_transactions",
    "activate_connection",
    "advance_exists_for_transaction",
    "assign_transaction_to_event",
    "category_has_children",
    "category_is_confirmed_on_any_transaction",
    "category_name_exists",
    "count_recent_sync_runs",
    "create_advance",
    "create_category",
    "create_connection",
    "create_event",
    "create_imported_transactions",
    "create_manual_account",
    "create_manual_transaction",
    "create_reimbursement",
    "create_rule",
    "create_transfer",
    "create_transfer_dismissal",
    "delete_advance",
    "delete_category",
    "delete_event",
    "delete_manual_account",
    "delete_manual_transaction",
    "delete_reimbursement",
    "delete_rule",
    "delete_rules_for_category",
    "delete_transfer",
    "earliest_transaction_dates_by_account",
    "event_ids_for_transactions",
    "find_pending_connection_id",
    "get_account",
    "get_advance",
    "get_category",
    "get_connection",
    "get_connection_credentials",
    "get_event",
    "get_fx_rates",
    "get_meal_vouchers_enabled",
    "get_rule",
    "get_tracking_start_date",
    "get_transaction",
    "get_transaction_event_id",
    "imported_stable_keys",
    "latest_fx_rate_fetched_at",
    "list_accounts",
    "list_advances",
    "list_all_transactions",
    "list_categories",
    "list_child_category_ids",
    "list_connections",
    "list_connections_without_logo",
    "list_event_candidates",
    "list_event_members",
    "list_events",
    "list_reimbursements",
    "list_rules",
    "list_sync_runs",
    "list_transactions",
    "list_transactions_by_ids",
    "list_transactions_in_period",
    "list_transfer_dismissals",
    "list_transfers",
    "mark_connection_synced",
    "move_category",
    "oldest_recent_sync_run_started_at",
    "prune_stale_pending_transactions",
    "record_sync_run",
    "rename_category",
    "rule_exists",
    "seed_default_categories",
    "set_account_alias",
    "set_account_appearance",
    "set_account_kind",
    "set_advance_status",
    "set_category_appearance",
    "set_confirmed_category",
    "set_connection_auth_state",
    "set_connection_logo",
    "set_event_status",
    "set_meal_vouchers_enabled",
    "set_suggested_categories",
    "set_tracking_start_date",
    "set_transaction_role",
    "sum_reimbursements_by_advance",
    "sum_reimbursements_by_participant",
    "transaction_is_linked",
    "transfer_exists_for_transaction",
    "unassign_transaction_from_event",
    "update_event",
    "update_manual_transaction",
    "upsert_account",
    "upsert_fx_rates",
    "upsert_transaction",
]
